apiVersion: apps/v1
kind: Deployment
metadata:
  name: ey-backend-nodejs
  namespace: rwa-tool
  labels:
    app: ey-backend-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ey-backend-nodejs
  template:
    metadata:
      labels:
        app: ey-backend-nodejs
    spec:
      containers:
        - name: ey-backend-nodejs
          image: gcr.io/coral-hull-356115/rwa-tool/ey-backend-nodejs:22.0731.2132
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: /usr/src/app/data/output
              name: output-file-path-app
      volumes:
        - name: output-file-path-app
          persistentVolumeClaim:
            claimName: output-file-path-app
---
apiVersion: v1
kind: Service
metadata:
  name: ey-backend-nodejs
  namespace: rwa-tool
  labels:
    app: ey-backend-nodejs
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ey-backend-nodejs
  type: NodePort