export const TABLE_NAME = {
    FILE: 'file',
    REPORT: 'report',
    ACTION_LOGS: 'action_logs',
    USER_INFO: 'user_info',
    ROLE_GROUP: 'role_group',
};

export const ENTITY_ACTION = {
    INSERT: 'INSERT',
    INSERT_BATCH: 'INSERT_BATCH',
    INSERT_OR_UPDATE: 'INSERT_OR_UPDATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    GET_PAGGING: 'GET_PAGGING',
    GET_PAGGING_UNION: 'GET_PAGGING_UNION',
    GET_COUNT: 'GET_COUNT',
    SELECT: 'SELECT',
};

export const LOGICAL = {
    AND: 'AND',
    OR: 'OR',
};

export const OPERATOR = {
    EQUAL: '=',
    NOT_EQUAL: '<>',
    IN: 'IN',
    NOT_IN: 'NOT IN',
    GREATER: '>',
    GREATER_OR_EQUAL: '>=',
    LESS: '<',
    LESS_OR_EQUAL: '<=',
    LIKE: 'LIKE',
    NOT_LIKE: 'NOT LIKE',
    IS_NULL: 'IS NULL',
    IS_NOT_NULL: 'IS NOT NULL',
    START_WITH: 'LIKE',
    END_WITH: 'LIKE',
    NOT_START_WITH: 'NOT LIKE',
    NOT_END_WITH: 'NOT LIKE',
    MATCH: 'MATCH',
};

export const FILE = {
    STG_INSTRUMENT_CONTRACT_MASTER: 'STG_INSTRUMENT_CONTRACT_MASTER',
    STG_BANK_POSITIONS: 'STG_BANK_POSITIONS',
    STG_SENSITIVITIES_FX: 'STG_SENSITIVITIES_FX',
    STG_SENSITIVITIES_GIRR: 'STG_SENSITIVITIES_GIRR',
    STG_PARTY_RATING_DETAILS: 'STG_PARTY_RATING_DETAILS',
    STG_PARTY_MASTER: 'STG_PARTY_MASTER',
    STG_CURVATURES_SHOCK: 'STG_CURVATURES_SHOCK',
    STG_PARTY_FINANCIALS: 'STG_PARTY_FINANCIALS',
    STG_INSTRUMENT_CONTRACT_MASTER_2: 'STG_INSTRUMENT_CONTRACT_MASTER_2',
    STG_NETTING: 'STG_NETTING',
    FINANCIAL_DATA_GL_ACTUAL_BALANCE: 'FINANCIAL_DATA_GL_ACTUAL_BALANCE',
    OPERATIONAL_RISK_LOSS_DATA: 'OPERATIONAL_RISK_LOSS_DATA',
};

export const FILE_HASHMAP = {
    STG_INSTRUMENT_CONTRACT_MASTER: 'STG_INSTRUMENT_CONTRACT_MASTER_HASHMAP',
    STG_BANK_POSITIONS: 'STG_BANK_POSITIONS_HASHMAP',
    STG_SENSITIVITIES_FX: 'STG_SENSITIVITIES_FX_HASHMAP',
    STG_SENSITIVITIES_GIRR: 'STG_SENSITIVITIES_GIRR_HASHMAP',
    STG_PARTY_RATING_DETAILS: 'STG_PARTY_RATING_DETAILS_HASHMAP',
    STG_PARTY_MASTER: 'STG_PARTY_MASTER_HASHMAP',
    STG_CURVATURES_SHOCK: 'STG_CURVATURES_SHOCK_HASHMAP',
    STG_PARTY_FINANCIALS: 'STG_PARTY_FINANCIALS_HASHMAP',
    STG_INSTRUMENT_CONTRACT_MASTER_2: 'STG_INSTRUMENT_CONTRACT_MASTER_2_HASHMAP',
    STG_NETTING: 'STG_NETTING_HASHMAP',
    FINANCIAL_DATA_GL_ACTUAL_BALANCE: 'FINANCIAL_DATA_GL_ACTUAL_BALANCE_HASHMAP',
    OPERATIONAL_RISK_LOSS_DATA: 'OPERATIONAL_RISK_LOSS_DATA_HASHMAP',
};

export const FILE_NAME = {
    STG_INSTRUMENT_CONTRACT_MASTER: 'STG_INSTRUMENT_CONTRACT_MASTER.csv',
    STG_BANK_POSITIONS: 'STG_BANK_POSITIONS.csv',
    STG_SENSITIVITIES_FX: 'STG_SENSITIVITIES_FX.csv',
    STG_SENSITIVITIES_GIRR: 'STG_SENSITIVITIES_GIRR.csv',
    STG_PARTY_RATING_DETAILS: 'STG_PARTY_RATING_DETAILS.csv',
    STG_PARTY_MASTER: 'STG_PARTY_MASTER.csv',
    STG_CURVATURES_SHOCK: 'STG_CURVATURES_SHOCK.csv',
    STG_PARTY_FINANCIALS: 'STG_PARTY_FINANCIALS.csv',
    STG_INSTRUMENT_CONTRACT_MASTER_2: 'STG_INSTRUMENT_CONTRACT_MASTER_2.csv',
    STG_NETTING: 'STG_NETTING.csv',
    FINANCIAL_DATA_GL_ACTUAL_BALANCE: 'FINANCIAL_DATA_GL_ACTUAL_BALANCE.csv',
    OPERATIONAL_RISK_LOSS_DATA: 'OPERATIONAL_RISK_LOSS_DATA.csv',
};

export const HASHMAP_KEY = {
    STG_INSTRUMENT_CONTRACT_MASTER: 'v_instrument_code',
    STG_BANK_POSITIONS: 'v_instrument_code',
    STG_SENSITIVITIES_FX: 'v_instrument_code',
    STG_SENSITIVITIES_GIRR: 'v_instrument_code',
    STG_PARTY_RATING_DETAILS: 'v_party_name',
    STG_PARTY_MASTER: 'v_cust_ref_code',
    STG_CURVATURES_SHOCK: 'v_ccy_code',
    STG_PARTY_FINANCIALS: 'v_cust_ref_code',
    STG_INSTRUMENT_CONTRACT_MASTER_2: 'v_instrument_code',
    STG_NETTING: 'v_netting_code',
    FINANCIAL_DATA_GL_ACTUAL_BALANCE: 'item',
    OPERATIONAL_RISK_LOSS_DATA: 'item',
};

export const MAPPING_CSV = {
    STG_INSTRUMENT_CONTRACT_MASTER: {
        FIC_MIS_DATE: 0,
        V_INSTRUMENT_CODE: 1,
        V_PRODUCT_CODE: 2,
        V_ISSUER_CODE: 3,
        V_ISSUER_TYPE: 4,
        V_CUST_REF_CODE: 5,
        N_LGD: 6,
        V_CCY_CODE: 7,
        V_CCY2_CODE: 8,
        F_OTC_IND: 9,
        D_EFFECTIVE_DATE: 10,
        D_MATURITY_DATE: 11,
        V_COUPON_TYPE: 12,
        N_COUPON_RATE: 13,
        D_ISSUE_DATE: 14,
        V_INT_TYPE_PAY: 15,
        N_INT_RATE_PAY: 16,
        D_REPRICING_DATE_PAY: 17,
        V_INT_TYPE_REC: 18,
        N_INT_RATE_REC: 19,
        D_REPRICING_DATE_REC: 20,
        F_APP_GUAR_CENTRAL_GOVT: 21,
        V_ISIN_ID: 22,
        D_MATURITY_DATE_FAR_LEG: 23,
        V_PARTY_ID: 24,
        XX_V_SRC_INSTRUMENT_CODE: 25,
        V_INSTRUMENT_DESC: 26,
        F_OPTIONAL: 27,
        V_OPTION_TYPE: 28,
        F_EXOTIC_UNDERLYING: 29,
        V_HEDGED_UNDERLYING_ASSET: 30,
        V_UNDERLYING_CD: 31,
        V_UNDERLYING_TYPE_CODE: 32,
        N_UNDERLYING_PRICE: 33,
        N_STRIKE_PRICE: 34,
        V_PRODUCT_TYPE: 35,
        D_MATURITY_DATE_UNDERLYING: 36,
    },
    STG_BANK_POSITIONS: {
        FIC_MIS_DATE: 0,
        V_INSTRUMENT_CODE: 1,
        V_INSTRUMENT_POSITION: 2,
        N_MTM_VALUE: 3,
        N_MTM_VALUE_LCY: 4,
        N_NOTIONAL_AMT_PAY: 5,
        N_NOTIONAL_AMT_RCV: 6,
        N_NOTIONAL_AMT_PAY_LCY: 7,
        N_NOTIONAL_AMT_RCV_LCY: 8,
        N_PNL: 9,
    },
    STG_SENSITIVITIES_FX: {
        FIC_MIS_DATE: 0,
        V_INSTRUMENT_CODE: 1,
        V_INSTRUMENT_POSITION: 2,
        N_DELTA_FX: 3,
        'N_VEGA_FX_0.5YEAR': 4,
        N_VEGA_FX_1YEAR: 5,
        N_VEGA_FX_3YEAR: 6,
        N_VEGA_FX_5YEAR: 7,
        N_VEGA_FX_10YEAR: 8,
        N_CURVATURE_FX: 9,
    },
    STG_SENSITIVITIES_GIRR: {
        FIC_MIS_DATE: 0,
        V_INSTRUMENT_CODE: 1,
        V_INSTRUMENT_POSITION: 2,
        V_CCY_CODE: 3,
        V_CCY2_CODE: 4,
        'N_DELTA_GIRR_1ST_CCY_0.25YEAR': 5,
        'N_DELTA_GIRR_1ST_CCY_0.5YEAR': 6,
        N_DELTA_GIRR_1ST_CCY_1YEAR: 7,
        N_DELTA_GIRR_1ST_CCY_2YEAR: 8,
        N_DELTA_GIRR_1ST_CCY_3YEAR: 9,
        N_DELTA_GIRR_1ST_CCY_5YEAR: 10,
        N_DELTA_GIRR_1ST_CCY_10YEAR: 11,
        N_DELTA_GIRR_1ST_CCY_15YEAR: 12,
        N_DELTA_GIRR_1ST_CCY_20YEAR: 13,
        N_DELTA_GIRR_1ST_CCY_30YEAR: 14,
        'N_DELTA_GIRR_2ND_CCY_0.25YEAR': 15,
        'N_DELTA_GIRR_2ND_CCY_0.5YEAR': 16,
        N_DELTA_GIRR_2ND_CCY_1YEAR: 17,
        N_DELTA_GIRR_2ND_CCY_2YEAR: 18,
        N_DELTA_GIRR_2ND_CCY_3YEAR: 19,
        N_DELTA_GIRR_2ND_CCY_5YEAR: 20,
        N_DELTA_GIRR_2ND_CCY_10YEAR: 21,
        N_DELTA_GIRR_2ND_CCY_15YEAR: 22,
        N_DELTA_GIRR_2ND_CCY_20YEAR: 23,
        N_DELTA_GIRR_2ND_CCY_30YEAR: 24,
        'N_VEGA_GIRR_1ST_CCY_0.5YEAR': 25,
        N_VEGA_GIRR_1ST_CCY_1YEAR: 26,
        N_VEGA_GIRR_1ST_CCY_3YEAR: 27,
        N_VEGA_GIRR_1ST_CCY_5YEAR: 28,
        N_VEGA_GIRR_1ST_CCY_10YEAR: 29,
        'N_VEGA_GIRR_2ND_CCY_0.5YEAR': 30,
        N_VEGA_GIRR_2ND_CCY_1YEAR: 31,
        N_VEGA_GIRR_2ND_CCY_3YEAR: 32,
        N_VEGA_GIRR_2ND_CCY_5YEAR: 33,
        N_VEGA_GIRR_2ND_CCY_10YEAR: 34,
        N_CURVATURE_GIRR_1ST_CCY: 35,
        N_CURVATURE_GIRR_2ND_CCY: 36,
    },
    STG_PARTY_RATING_DETAILS: {
        FIC_MIS_DATE: 0,
        V_RATING_SRC_CODE: 1,
        V_PARTY_NAME: 2,
        V_RATING_CODE: 3,
        F_RATING_ELIGIBILITY: 4,
        V_CUST_REF_CODE: 5,
    },
    STG_PARTY_MASTER: {
        FIC_MIS_DATE: 0,
        V_CUST_REF_CODE: 1,
        V_PARTY_NAME: 2,
        V_LOCATION_CODE: 3,
        D_DATE_OF_BIRTH: 4,
        V_INDUSTRY_CODE: 5,
        V_PARTY_TYPE_CODE: 6,
        N_NO_OF_EMPOLYEES: 7,
        LOAN_CLASSIFICATION: 8,
    },
    STG_CURVATURES_SHOCK: {
        FIC_MIS_DATE: 0,
        V_CCY_CODE: 1,
        V_CURVATURE_GIRR_PNL: 2,
        V_CURVATURE_GIRR_UP: 3,
        V_CURVATURE_GIRR_DOWN: 4,
        V_CURVATURE_FX_PNL: 5,
        V_CURVATURE_FX_UP: 6,
        V_CURVATURE_FX_DOWN: 7,
    },
    STG_PARTY_FINANCIALS: {
        FIC_MIS_DATE: 0,
        V_CUST_REF_CODE: 1,
        N_TOTAL_ASSETS: 2,
        N_TOTAL_REVENUE: 3,
        D_BS_CREATION_DATE: 4,
        V_CCY_CODE: 5,
        XX_N_ANNUAL_DEBT: 6,
        XX_N_ANNUAL_INCOME: 7,
        N_LEVERAGE_RATIO: 8,
        N_TOTAL_EQUITY: 9,
        XX_F_FIN_STATE_TYPE: 10,
        XX_F_AUDITED_REPORT: 11,
        N_TOTAL_DEBT: 12,
    },
    STG_INSTRUMENT_CONTRACT_MASTER_2: {
        FIC_MIS_DATE: 0,
        V_INSTRUMENT_CODE: 1,
        V_ASSET_CLASS: 2,
        V_SUB_CLASS: 3,
        V_ISSUER_CODE: 4,
        V_ISSUER_TYPE: 5,
        V_CCY_CODE: 6,
        V_CTR_CCY_CODE: 7,
        F_OTC_IND: 8,
        D_EFFECTIVE_DATE: 9,
        D_MATURITY_DATE: 10,
        V_PRODUCT_CODE: 11,
        V_INT_TYPE_PAY: 12,
        N_INT_RATE_PAY: 13,
        D_REPRICING_DATE_PAY: 14,
        V_INT_TYPE_REC: 15,
        N_INT_RATE_REC: 16,
        D_REPRICING_DATE_REC: 17,
        F_APP_GUAR_CENTRAL_GOVT: 18,
        V_ISIN_ID: 19,
        V_PARTY_ID: 20,
        XX_V_SRC_INSTRUMENT_CODE: 21,
        V_INSTRUMENT_DESC: 22,
        V_OPTION_TYPE: 23,
        V_HEDGED_UNDERLYING_ASSET: 24,
        V_UNDERLYING_CD: 25,
        V_UNDERLYING_TYPE_CODE: 26,
        N_UNDERLYING_PRICE: 27,
        N_STRIKE_PRICE: 28,
        V_PRODUCT_TYPE: 29,
        V_PAIR_CCY: 30,
        V_INSTRUMENT_POSITION: 31,
        N_NOTIONAL_AMT: 32,
        N_MARKET_VALUE: 33,
        D_MATURITY_DATE_UNDERLYING: 34,
        V_COLLATERAL_ID: 35,
        N_COLLATERAL_CCP_AMT: 36,
        N_COLLATERAL_BANK_AMT: 37,
        F_MARGIN: 38,
        F_CENTRALLY_CLEARED: 39,
        N_MARGIN_FREQUENCY: 40,
        V_NETTING_CODE: 41,
        SECTOR_OF_COUNTERPARTY: 42,
        CREDIT_RATING_OF_COUNTERPARTY: 43,
        INTEREST_RATE: 44,
    },
    STG_NETTING: {
        V_NETTING_CODE: 0,
        N_THRESHOLD: 1,
        N_MTA: 2,
        N_NICA: 3,
        N_NET: 4,
        N_EFFECTIVEMATURITY: 5,
    },
    FINANCIAL_DATA_GL_ACTUAL_BALANCE: {
        Item: 0,
        'Actual balance in quarter n-11': 1,
        'Actual balance in quarter n-10': 2,
        'Actual balance in quarter n-9': 3,
        'Actual balance in quarter n-8': 4,
        'Actual balance in quarter n-7': 5,
        'Actual balance in quarter n-6': 6,
        'Actual balance in quarter n-5': 7,
        'Actual balance in quarter n-4': 8,
        'Actual balance in quarter n-3': 9,
        'Actual balance in quarter n-2': 10,
        'Actual balance in quarter n-1': 11,
        'Actual balance in quarter n': 12,
    },
    OPERATIONAL_RISK_LOSS_DATA: {
        Item: 0,
        'Quarter n-19': 1,
        'Quarter n-18': 2,
        'Quarter n-17': 3,
        'Quarter n-16': 4,
        'Quarter n-15': 5,
        'Quarter n-14': 6,
        'Quarter n-13': 7,
        'Quarter n-12': 8,
        'Quarter n-11': 9,
        'Quarter n-10': 10,
        'Quarter n-9': 11,
        'Quarter n-8': 12,
        'Quarter n-7': 13,
        'Quarter n-6': 14,
        'Quarter n-5': 15,
        'Quarter n-4': 16,
        'Quarter n-3': 17,
        'Quarter n-2': 18,
        'Quarter n-1': 19,
        'Quarter n': 20,
    },
};

export const SHEET_NAMES = [
    'STG_INSTRUMENT_CONTRACT_MASTER',
    'STG_BANK_POSITIONS',
    'STG_SENSITIVITIES_FX',
    'STG_SENSITIVITIES_GIRR',
    'STG_PARTY_RATING_DETAILS',
    'STG_PARTY_MASTER',
    'STG_CURVATURES_SHOCK',
    'STG_PARTY_FINANCIALS',
    'STG_INSTRUMENT_CONTRACT_MASTER_',
    'STG_NETTING',
    'FINANCIAL_DATA_GL_ACTUAL_BALANC',
    'OPERATIONAL_RISK_LOSS_DATA',
];

export const SHEET_NAMES_HASHMAP = {
    STG_INSTRUMENT_CONTRACT_MASTER: 'STG_INSTRUMENT_CONTRACT_MASTER',
    STG_BANK_POSITIONS: 'STG_BANK_POSITIONS',
    STG_SENSITIVITIES_FX: 'STG_SENSITIVITIES_FX',
    STG_SENSITIVITIES_GIRR: 'STG_SENSITIVITIES_GIRR',
    STG_PARTY_RATING_DETAILS: 'STG_PARTY_RATING_DETAILS',
    STG_PARTY_MASTER: 'STG_PARTY_MASTER',
    STG_CURVATURES_SHOCK: 'STG_CURVATURES_SHOCK',
    STG_PARTY_FINANCIALS: 'STG_PARTY_FINANCIALS',
    STG_INSTRUMENT_CONTRACT_MASTER_: 'STG_INSTRUMENT_CONTRACT_MASTER_2',
    STG_NETTING: 'STG_NETTING',
    FINANCIAL_DATA_GL_ACTUAL_BALANC: 'FINANCIAL_DATA_GL_ACTUAL_BALANCE',
    OPERATIONAL_RISK_LOSS_DATA: 'OPERATIONAL_RISK_LOSS_DATA',
};

export const MAPPING_FIELD_NAMES = {
    STG_INSTRUMENT_CONTRACT_MASTER: {
        FIC_MIS_DATE: 'fic_mis_date',
        V_INSTRUMENT_CODE: 'v_instrument_code',
        V_PRODUCT_CODE: 'v_product_code',
        V_ISSUER_CODE: 'v_issuer_code',
        V_ISSUER_TYPE: 'v_issuer_type',
        V_CUST_REF_CODE: 'v_cust_ref_code',
        N_LGD: 'n_lgd',
        V_CCY_CODE: 'v_ccy_code',
        V_CCY2_CODE: 'v_ccy2_code',
        F_OTC_IND: 'f_otc_ind',
        D_EFFECTIVE_DATE: 'd_effective_date',
        D_MATURITY_DATE: 'd_maturity_date',
        V_COUPON_TYPE: 'v_coupon_type',
        N_COUPON_RATE: 'n_coupon_rate',
        D_ISSUE_DATE: 'd_issue_date',
        V_INT_TYPE_PAY: 'v_int_type_pay',
        N_INT_RATE_PAY: 'n_int_rate_pay',
        D_REPRICING_DATE_PAY: 'd_repricing_date_pay',
        V_INT_TYPE_REC: 'v_int_type_rec',
        N_INT_RATE_REC: 'n_int_rate_rec',
        D_REPRICING_DATE_REC: 'd_repricing_date_rec',
        F_APP_GUAR_CENTRAL_GOVT: 'f_app_guar_central_govt',
        V_ISIN_ID: 'v_isin_id',
        D_MATURITY_DATE_FAR_LEG: 'd_maturity_date_far_leg',
        V_PARTY_ID: 'v_party_id',
        XX_V_SRC_INSTRUMENT_CODE: 'xx_v_src_instrument_code',
        V_INSTRUMENT_DESC: 'v_instrument_desc',
        F_OPTIONAL: 'f_optional',
        V_OPTION_TYPE: 'v_option_type',
        F_EXOTIC_UNDERLYING: 'f_exotic_underlying',
        V_HEDGED_UNDERLYING_ASSET: 'v_hedged_underlying_asset',
        V_UNDERLYING_CD: 'v_underlying_cd',
        V_UNDERLYING_TYPE_CODE: 'v_underlying_type_code',
        N_UNDERLYING_PRICE: 'n_underlying_price',
        N_STRIKE_PRICE: 'n_strike_price',
        V_PRODUCT_TYPE: 'v_product_type',
        D_MATURITY_DATE_UNDERLYING: 'd_maturity_date_underlying',
    },
    STG_BANK_POSITIONS: {
        FIC_MIS_DATE: 'fic_mis_date',
        V_INSTRUMENT_CODE: 'v_instrument_code',
        V_INSTRUMENT_POSITION: 'v_instrument_position',
        N_MTM_VALUE: 'n_mtm_value',
        N_MTM_VALUE_LCY: 'n_mtm_value_lcy',
        N_NOTIONAL_AMT_PAY: 'n_notional_amt_pay',
        N_NOTIONAL_AMT_RCV: 'n_notional_amt_rcv',
        N_NOTIONAL_AMT_PAY_LCY: 'n_notional_amt_pay_lcy',
        N_NOTIONAL_AMT_RCV_LCY: 'n_notional_amt_rcv_lcy',
        N_PNL: 'n_pnl',
    },
    STG_SENSITIVITIES_FX: {
        FIC_MIS_DATE: 'fic_mis_date',
        V_INSTRUMENT_CODE: 'v_instrument_code',
        V_INSTRUMENT_POSITION: 'v_instrument_position',
        N_DELTA_FX: 'n_delta_fx',
        'N_VEGA_FX_0.5YEAR': 'n_vega_fx_half_a_year',
        N_VEGA_FX_1YEAR: 'n_vega_fx_1year',
        N_VEGA_FX_3YEAR: 'n_vega_fx_3year',
        N_VEGA_FX_5YEAR: 'n_vega_fx_5year',
        N_VEGA_FX_10YEAR: 'n_vega_fx_10year',
        N_CURVATURE_FX: 'n_curvature_fx',
    },
    STG_SENSITIVITIES_GIRR: {
        FIC_MIS_DATE: 'fic_mis_date',
        V_INSTRUMENT_CODE: 'v_instrument_code',
        V_INSTRUMENT_POSITION: 'v_instrument_position',
        V_CCY_CODE: 'v_ccy_code',
        V_CCY2_CODE: 'v_ccy2_code',
        'N_DELTA_GIRR_1ST_CCY_0.25YEAR': 'n_delta_girr_1st_ccy_a_quarter_of_year',
        'N_DELTA_GIRR_1ST_CCY_0.5YEAR': 'n_delta_girr_1st_ccy_half_a_year',
        N_DELTA_GIRR_1ST_CCY_1YEAR: 'n_delta_girr_1st_ccy_1year',
        N_DELTA_GIRR_1ST_CCY_2YEAR: 'n_delta_girr_1st_ccy_2year',
        N_DELTA_GIRR_1ST_CCY_3YEAR: 'n_delta_girr_1st_ccy_3year',
        N_DELTA_GIRR_1ST_CCY_5YEAR: 'n_delta_girr_1st_ccy_5year',
        N_DELTA_GIRR_1ST_CCY_10YEAR: 'n_delta_girr_1st_ccy_10year',
        N_DELTA_GIRR_1ST_CCY_15YEAR: 'n_delta_girr_1st_ccy_15year',
        N_DELTA_GIRR_1ST_CCY_20YEAR: 'n_delta_girr_1st_ccy_20year',
        N_DELTA_GIRR_1ST_CCY_30YEAR: 'n_delta_girr_1st_ccy_30year',
        'N_DELTA_GIRR_2ND_CCY_0.25YEAR': 'n_delta_girr_2nd_ccy_a_quarter_of_year',
        'N_DELTA_GIRR_2ND_CCY_0.5YEAR': 'n_delta_girr_2nd_ccy_half_a_year',
        N_DELTA_GIRR_2ND_CCY_1YEAR: 'n_delta_girr_2nd_ccy_1year',
        N_DELTA_GIRR_2ND_CCY_2YEAR: 'n_delta_girr_2nd_ccy_2year',
        N_DELTA_GIRR_2ND_CCY_3YEAR: 'n_delta_girr_2nd_ccy_3year',
        N_DELTA_GIRR_2ND_CCY_5YEAR: 'n_delta_girr_2nd_ccy_5year',
        N_DELTA_GIRR_2ND_CCY_10YEAR: 'n_delta_girr_2nd_ccy_10year',
        N_DELTA_GIRR_2ND_CCY_15YEAR: 'n_delta_girr_2nd_ccy_15year',
        N_DELTA_GIRR_2ND_CCY_20YEAR: 'n_delta_girr_2nd_ccy_20year',
        N_DELTA_GIRR_2ND_CCY_30YEAR: 'n_delta_girr_2nd_ccy_30year',
        'N_VEGA_GIRR_1ST_CCY_0.5YEAR': 'n_vega_girr_1st_ccy_half_a_year',
        N_VEGA_GIRR_1ST_CCY_1YEAR: 'n_vega_girr_1st_ccy_1year',
        N_VEGA_GIRR_1ST_CCY_3YEAR: 'n_vega_girr_1st_ccy_3year',
        N_VEGA_GIRR_1ST_CCY_5YEAR: 'n_vega_girr_1st_ccy_5year',
        N_VEGA_GIRR_1ST_CCY_10YEAR: 'n_vega_girr_1st_ccy_10year',
        'N_VEGA_GIRR_2ND_CCY_0.5YEAR': 'n_vega_girr_2nd_ccy_half_a_year',
        N_VEGA_GIRR_2ND_CCY_1YEAR: 'n_vega_girr_2nd_ccy_1year',
        N_VEGA_GIRR_2ND_CCY_3YEAR: 'n_vega_girr_2nd_ccy_3year',
        N_VEGA_GIRR_2ND_CCY_5YEAR: 'n_vega_girr_2nd_ccy_5year',
        N_VEGA_GIRR_2ND_CCY_10YEAR: 'n_vega_girr_2nd_ccy_10year',
        N_CURVATURE_GIRR_1ST_CCY: 'n_curvature_girr_1st_ccy',
        N_CURVATURE_GIRR_2ND_CCY: 'n_curvature_girr_2nd_ccy',
    },
    STG_PARTY_RATING_DETAILS: {
        FIC_MIS_DATE: 'fic_mis_date',
        V_RATING_SRC_CODE: 'v_rating_src_code',
        V_PARTY_NAME: 'v_party_name',
        V_RATING_CODE: 'v_rating_code',
        F_RATING_ELIGIBILITY: 'f_rating_eligibility',
        V_CUST_REF_CODE: 'v_cust_ref_code',
    },
    STG_PARTY_MASTER: {
        FIC_MIS_DATE: 'fic_mis_date',
        V_CUST_REF_CODE: 'v_cust_ref_code',
        V_PARTY_NAME: 'v_party_name',
        V_LOCATION_CODE: 'v_location_code',
        D_DATE_OF_BIRTH: 'd_date_of_birth',
        V_INDUSTRY_CODE: 'v_industry_code',
        V_PARTY_TYPE_CODE: 'v_party_type_code',
        N_NO_OF_EMPOLYEES: 'n_no_of_empolyees',
        LOAN_CLASSIFICATION: 'loan_classification',
    },
    STG_CURVATURES_SHOCK: {
        FIC_MIS_DATE: 'fic_mis_date',
        V_CCY_CODE: 'v_ccy_code',
        V_CURVATURE_GIRR_PNL: 'v_curvature_girr_pnl',
        V_CURVATURE_GIRR_UP: 'v_curvature_girr_up',
        V_CURVATURE_GIRR_DOWN: 'v_curvature_girr_down',
        V_CURVATURE_FX_PNL: 'v_curvature_fx_pnl',
        V_CURVATURE_FX_UP: 'v_curvature_fx_up',
        V_CURVATURE_FX_DOWN: 'v_curvature_fx_down',
    },
    STG_PARTY_FINANCIALS: {
        FIC_MIS_DATE: 'fic_mis_date',
        V_CUST_REF_CODE: 'v_cust_ref_code',
        N_TOTAL_ASSETS: 'n_total_assets',
        N_TOTAL_REVENUE: 'n_total_revenue',
        D_BS_CREATION_DATE: 'd_bs_creation_date',
        V_CCY_CODE: 'v_ccy_code',
        XX_N_ANNUAL_DEBT: 'xx_n_annual_debt',
        XX_N_ANNUAL_INCOME: 'xx_n_annual_income',
        N_LEVERAGE_RATIO: 'n_leverage_ratio',
        N_TOTAL_EQUITY: 'n_total_equity',
        XX_F_FIN_STATE_TYPE: 'xx_f_fin_state_type',
        XX_F_AUDITED_REPORT: 'xx_f_audited_report',
        N_TOTAL_DEBT: 'n_total_debt',
    },
    STG_INSTRUMENT_CONTRACT_MASTER_2: {
        FIC_MIS_DATE: 'fic_mis_date',
        V_INSTRUMENT_CODE: 'v_instrument_code',
        V_ASSET_CLASS: 'v_asset_class',
        V_SUB_CLASS: 'v_sub_class',
        V_ISSUER_CODE: 'v_issuer_code',
        V_ISSUER_TYPE: 'v_issuer_type',
        V_CCY_CODE: 'v_ccy_code',
        V_CTR_CCY_CODE: 'v_ctr_ccy_code',
        F_OTC_IND: 'f_otc_ind',
        D_EFFECTIVE_DATE: 'd_effective_date',
        D_MATURITY_DATE: 'd_maturity_date',
        V_PRODUCT_CODE: 'v_product_code',
        V_INT_TYPE_PAY: 'v_int_type_pay',
        N_INT_RATE_PAY: 'n_int_rate_pay',
        D_REPRICING_DATE_PAY: 'd_repricing_date_pay',
        V_INT_TYPE_REC: 'v_int_type_rec',
        N_INT_RATE_REC: 'n_int_rate_rec',
        D_REPRICING_DATE_REC: 'd_repricing_date_rec',
        F_APP_GUAR_CENTRAL_GOVT: 'f_app_guar_central_govt',
        V_ISIN_ID: 'v_isin_id',
        V_PARTY_ID: 'v_party_id',
        XX_V_SRC_INSTRUMENT_CODE: 'xx_v_src_instrument_code',
        V_INSTRUMENT_DESC: 'v_instrument_desc',
        V_OPTION_TYPE: 'v_option_type',
        V_HEDGED_UNDERLYING_ASSET: 'v_hedged_underlying_asset',
        V_UNDERLYING_CD: 'v_underlying_cd',
        V_UNDERLYING_TYPE_CODE: 'v_underlying_type_code',
        N_UNDERLYING_PRICE: 'n_underlying_price',
        N_STRIKE_PRICE: 'n_strike_price',
        V_PRODUCT_TYPE: 'v_product_type',
        V_PAIR_CCY: 'v_pair_ccy',
        V_INSTRUMENT_POSITION: 'v_instrument_position',
        N_NOTIONAL_AMT: 'n_notional_amt',
        N_MARKET_VALUE: 'n_market_value',
        D_MATURITY_DATE_UNDERLYING: 'd_maturity_date_underlying',
        V_COLLATERAL_ID: 'v_collateral_id',
        N_COLLATERAL_CCP_AMT: 'n_collateral_ccp_amt',
        N_COLLATERAL_BANK_AMT: 'n_collateral_bank_amt',
        F_MARGIN: 'f_margin',
        F_CENTRALLY_CLEARED: 'f_centrally_cleared',
        N_MARGIN_FREQUENCY: 'n_margin_frequency',
        V_NETTING_CODE: 'v_netting_code',
        SECTOR_OF_COUNTERPARTY: 'sector_of_counterparty',
        CREDIT_RATING_OF_COUNTERPARTY: 'credit_rating_of_counterparty',
        INTEREST_RATE: 'interest_rate',
    },
    STG_NETTING: {
        V_NETTING_CODE: 'v_netting_code',
        N_THRESHOLD: 'n_threshold',
        N_MTA: 'n_mta',
        N_NICA: 'n_nica',
        N_NET: 'n_net',
        N_EFFECTIVEMATURITY: 'n_effectivematurity',
    },
    FINANCIAL_DATA_GL_ACTUAL_BALANCE: {
        Item: 'item',
        'Actual balance in quarter n-11': 'actual_balance_in_quarter_n_11',
        'Actual balance in quarter n-10': 'actual_balance_in_quarter_n_10',
        'Actual balance in quarter n-9': 'actual_balance_in_quarter_n_9',
        'Actual balance in quarter n-8': 'actual_balance_in_quarter_n_8',
        'Actual balance in quarter n-7': 'actual_balance_in_quarter_n_7',
        'Actual balance in quarter n-6': 'actual_balance_in_quarter_n_6',
        'Actual balance in quarter n-5': 'actual_balance_in_quarter_n_5',
        'Actual balance in quarter n-4': 'actual_balance_in_quarter_n_4',
        'Actual balance in quarter n-3': 'actual_balance_in_quarter_n_3',
        'Actual balance in quarter n-2': 'actual_balance_in_quarter_n_2',
        'Actual balance in quarter n-1': 'actual_balance_in_quarter_n_1',
        'Actual balance in quarter n': 'actual_balance_in_quarter_n',
    },
    OPERATIONAL_RISK_LOSS_DATA: {
        Item: 'item',
        'Quarter n-19': 'quarter_n_19',
        'Quarter n-18': 'quarter_n_18',
        'Quarter n-17': 'quarter_n_17',
        'Quarter n-16': 'quarter_n_16',
        'Quarter n-15': 'quarter_n_15',
        'Quarter n-14': 'quarter_n_14',
        'Quarter n-13': 'quarter_n_13',
        'Quarter n-12': 'quarter_n_12',
        'Quarter n-11': 'quarter_n_11',
        'Quarter n-10': 'quarter_n_10',
        'Quarter n-9': 'quarter_n_9',
        'Quarter n-8': 'quarter_n_8',
        'Quarter n-7': 'quarter_n_7',
        'Quarter n-6': 'quarter_n_6',
        'Quarter n-5': 'quarter_n_5',
        'Quarter n-4': 'quarter_n_4',
        'Quarter n-3': 'quarter_n_3',
        'Quarter n-2': 'quarter_n_2',
        'Quarter n-1': 'quarter_n_1',
        'Quarter n': 'quarter_n',
    },
};

export const ROLE_NAME = {
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    EDIT_PARAMETERS: 'EDIT_PARAMETERS',
    UPLOAD_FILE: 'UPLOAD_FILE',
    VIEW_REPORT: 'VIEW_REPORT',
    DELETE_REPORT: 'DELETE_REPORT',
    CREATE_ROLE: 'CREATE_ROLE',
    UPDATE_ROLE: 'UPDATE_ROLE',
};

export const ROLE_NAME_ROLE_ID = {
    CREATE_USER: 1,
    UPDATE_USER: 2,
    DELETE_USER: 3,
    EDIT_PARAMETERS: 4,
    UPLOAD_FILE: 5,
    VIEW_REPORT: 6,
    DELETE_REPORT: 7,
    CREATE_ROLE: 8,
    UPDATE_ROLE: 9,
};

export const FILE_PATH = {
    OUTPUT: `${process.cwd()}/data/output`,
    INPUT: `${process.cwd()}/data/input`,
    TEMP: `${process.cwd()}/data/temp`,
};
